"""empty message

Revision ID: 37acb9f356f1
Revises: 800f7272538e
Create Date: 2024-10-16 21:32:55.694774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37acb9f356f1'
down_revision: Union[str, None] = '800f7272538e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'motivation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'motivation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
