"""empty message

Revision ID: 5b7dc58d66a5
Revises: e8724e716c41
Create Date: 2024-10-17 20:44:58.772914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7dc58d66a5'
down_revision: Union[str, None] = 'e8724e716c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('done', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'done')
    # ### end Alembic commands ###
